[workspace]

[package]
name = "fibonacci-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
num-bigint = "0.4"
num-traits = "0.2"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "fibonacci"
harness = false

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
opt-level = 3